---
title: "finalproj"
output: html_document
---

```{r}
library(tidyverse)
# Replace with your Google Sheet's public CSV URL
# (File > Share > Publish to web > CSV)
rankings <- "https://docs.google.com/spreadsheets/d/e/2PACX-1vSLdemlReTZft5wRLflBLDhULFFOdexE_dd6voqTNTfYe0NOwfvVyCoJ_6WiN_q7rT1yKZ9tNo-xIwW/pub?output=csv"

# Read directly from the URL
rat_ratings <- read_csv(rankings)

# View the data
glimpse(rat_ratings)
```
```{r}

cities <- "https://docs.google.com/spreadsheets/d/e/2PACX-1vSiB6dGOgnjEe27tNq6KEOAGKAy3FpkiLx34EU7Yp-JUrTdYXBotRNpnbgxx8pQtjE8YyIEB2FlNEfo/pub?gid=88512101&single=true&output=csv"

# Read directly from the URL
cities <- read_csv(cities)

# View the data
glimpse(cities)

```



```{r}
# Calculate statistics on each year
city_stat <- city_funding |> 
  summarise(
    twentytwentymean = mean(`2,020`),
    twentysd = sd(`2,020`),
    n = n(),
    twentytwentymin = min(`2,020`),
    twentytwentymax = max(`2,020`)
  )

```


```{r}
# Calculate statistics on each year
city_stat <- city_funding |> 
  summarise(
    twentyonemean = mean("2,021"),
    twentyonesd = sd("2,021"),
    n = n(),
    twentyonemin = min("2,021"),
    twentyonemax = max("2,021")
  )


```


```{r}
# T-test comparing rankings of two specific cities
twenty_data <- cities |> filter(year == `2,020`) |> pull(rating)
twentyone_data <- cities |> filter(year == `2,021`) |> pull(rating)

t.test(twenty_data, twentyone_data, paired = FALSE)
```
```{r}
# T-test comparing rankings of two specific cities
chicago_data <- rankings |> filter(city == "Chicago, Ill.") |> pull(rating)
nyc_data <- rankings |> filter(city == "New York City, NY") |> pull(rating)

t.test(chicago_data, nyc_data, paired = FALSE)
```


```{r anova-test}
# Run one-way ANOVA
anova_result <- aov(year ~ chicago_data, data = cities)
summary(anova_result)
```
```{r}
model <- lm(`2,021` ~ `Cities`, data = cityfunding)

summary(model)
```

Once a year the rats run this city. Pest Control Orkin creates a "rattiest city rating" on which city has the most rats per capita. Chicago has led the charts the past 10 years and New York has always followed. However, rodent control or general sanition funding has a relationship to how major cities are able to control their rodent population. 
